#! /bin/bash

#SET UP THE REPOSITORY
#Update the apt package index and install packages to allow apt to use a repository over HTTPS:

sudo apt-get update -y

sudo apt-get install \
    ca-certificates \
    curl \
    gnupg \
    lsb-release -y

#Add Docker’s official GPG key:

sudo mkdir -p /etc/apt/keyrings -y

curl -fsSL https://download.docker.com/linux/ubuntu/gpg |\
 sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg -y

#Use the following command to set up the repository:

echo \
  "deb [arch=$(dpkg --print-architecture) \
signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null -y

#INSTALL DOCKER ENGINE
#Update the apt package index:

sudo apt-get update -y

#Install Docker Engine, containerd, and Docker Compose.

sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin
